apiVersion: v1
kind: Service
metadata:
  name: {{ include "orion.fullname" . }}
  labels:
    {{- include "orion.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      protocol: TCP
{{ if (and (eq .Values.api.service.type "NodePort") (not (empty .Values.api.service.nodePort))) }}
      nodePort: {{ .Values.api.service.nodePort }}
{{ end }}
  selector:
    {{- include "orion.selectorLabels" . | nindent 4 }}
