# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: main
charts:
  - charts/prefect-agent
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
helm-extra-args: --timeout 600s
namespace: prefect
